# Generated by Django 5.2.6 on 2025-10-25 12:44

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('institution', 'Institution'), ('lecturer', 'Lecturer'), ('student', 'Student')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')])),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('idcard_back', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('idcard_front', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('residence_front', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('residence_back', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('x_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tiktok_link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_generated', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_achievement', models.CharField(max_length=255)),
                ('experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('free_time', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format must be HH:MM-HH:MM (e.g. 09:00-17:00)', regex='^(?:[01]\\d|2[0-3]):[0-5]\\d-(?:[01]\\d|2[0-3]):[0-5]\\d$')])),
                ('institutions', models.ManyToManyField(related_name='lecturers', to='api.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=1000)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_course_path)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('schedule', models.JSONField(default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.institution')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studying_level', models.CharField(choices=[('primary', 'Primary'), ('intermediate', 'Intermediate'), ('high', 'High'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('none', 'None')], max_length=20)),
                ('interesting_keywords', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Enter values separated by commas (e.g. Physics, Mathematics, Programming, etc.).', regex='^[^,]+(,\\s*[^,]+)+$')])),
                ('responsible_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')])),
                ('responsible_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('courses', models.ManyToManyField(related_name='students', to='api.course')),
                ('institutions', models.ManyToManyField(related_name='students', to='api.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
