# Generated by Django 5.2.6 on 2025-10-31 14:08

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')])),
                ('personal_image', models.ImageField(upload_to=api.models.upload_staff_path)),
                ('idcard_back', models.ImageField(blank=True, null=True, upload_to=api.models.upload_staff_path)),
                ('idcard_front', models.ImageField(blank=True, null=True, upload_to=api.models.upload_staff_path)),
                ('residence_front', models.ImageField(blank=True, null=True, upload_to=api.models.upload_staff_path)),
                ('residence_back', models.ImageField(blank=True, null=True, upload_to=api.models.upload_staff_path)),
                ('duty', models.CharField(max_length=255)),
                ('salary', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
