# Generated by Django 5.2.6 on 2025-12-05 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_capacity_course_level_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='marked_lecturers',
            field=models.ManyToManyField(blank=True, related_name='marked_by_institutions', to='api.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10), default=list, size=None),
        ),
    ]
