# Generated by Django 5.2.6 on 2025-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coursepayment_institutionsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
