# Generated by Django 5.2.6 on 2025-12-15 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_institution_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='up_time',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format must be HH:MM-HH:MM (e.g. 09:00-17:00)', regex='^(?:[01]\\d|2[0-3]):[0-5]\\d-(?:[01]\\d|2[0-3]):[0-5]\\d$')]),
        ),
    ]
