# Generated by Django 5.2.6 on 2025-12-15 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_institution_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='up_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10), default=list, size=None),
        ),
    ]
