from django.urls import path
from .views import *
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('home/feed/', HomeFeedView.as_view()),
    path('ai/doc/', DocumentCheckView.as_view()),
    path("notifications/", NotificationsView.as_view()),
    path("course/<int:course_id>/progress/", CourseProgressView.as_view()),
    path("explore/", ExploreSearchView.as_view()),
    path("course/<int:course_id>/", CourseDetailView.as_view()),
    path("course/<int:course_id>/students/", ExpectedStudentsView.as_view()),

    path('registration/signup/', SignupView.as_view()),
    path('registration/login/', LoginView.as_view()),
    path('registration/otp/', OTPView.as_view()),
    path('registration/is-verified/', IsVerifiedView.as_view()),
    path('registration/refresh/', TokenRefreshView.as_view()),

    path('institution/verify/', InstitutionVerificationView.as_view()),
    path('institution/total-students/', InstitutionTotalStudentsView.as_view()),
    path('institution/total-lecturers/', InstitutionTotalLecturersView.as_view()),
    path('institution/total-staff/', InstitutionTotalStaffView.as_view()),
    path('institution/active-students/', InstitutionActiveStudentsView.as_view()),
    path('institution/active-lecturers/', InstitutionActiveLecturersView.as_view()),
    path('institution/active-staff/', InstitutionActiveStaffView.as_view()),
    path('institution/students-list/', InstitutionStudentsListView.as_view()),
    path('institution/lecturers-list/', InstitutionLecturersListView.as_view()),
    path('institution/staff-list/', InstitutionStaffListView.as_view()),
    path('institution/schedule/', InstitutionWeeklyScheduleView.as_view()),
    path('institution/create-post/', InstitiutionCreatePostView.as_view()),
    path('institution/create-course/', InstitutionCreateCourseView.as_view()),
    path('institution/edit-course/<int:course_id>/', InstitutionEditCourseView.as_view()),
    path("institution/my-profile/", InstitutionSelfProfileView.as_view()),
    path("institution/profile/<str:username>/", InstitutionPublicProfileView.as_view()),
    path("institution/<str:username>/posts/", InstitutionPostsView.as_view()),
    path("institution/<str:username>/courses/", InstitutionCoursesView.as_view()),
    path("institution/edit-profile/", InstitutionEditProfileView.as_view()),
    path("institution/student/<int:student_id>/", InstitutionViewStudentProfile.as_view()),
    path("institution/lecturer/<int:lecturer_id>/", InstitutionViewLecturerProfile.as_view()),
    path("institution/staff/create/", StaffCreateView.as_view()),
    path("institution/staff/<int:staff_id>/", StaffDetailView.as_view()),
    path("institution/staff/<int:staff_id>/edit/", StaffEditView.as_view()),
    path("institution/staff/<int:staff_id>/delete/", StaffDeleteView.as_view()),
    path("institution/job/create/", InstitutionCreateJobView.as_view()),
    path("institution/<str:username>/jobs/", InstitutionJobsListView.as_view()),
    path("institution/job/<int:job_id>/", JobDetailView.as_view()),
    path("institution/job/<int:job_id>/applications/", InstitutionJobApplicationsView.as_view()),
    path("institution/course/<int:course_id>/attendance/", InstitutionCourseAttendanceSummaryView.as_view()),
    path("institution/is-lecturer-free/<int:lecturer_id>/", LecturerScheduleCheckView.as_view()),
    path("institution/mark-lecturer/", InstitutionAddMarkerView.as_view()),
    path("institution/marked-lecturers/", InstitutionMarkedLecturersView.as_view()),
    path("institution/is-marked/<int:lecturer_id>/", InstitutionIsMarkedView.as_view()),
    path("institution/remove-marked/<int:lecturer_id>/", InstitutionRemoveMarkerView.as_view()),
    path("institution/add-payment-method/", InstitutionSetupPaymentsView.as_view()),
    path("institution/subscribe/", CreateInstitutionSubscriptionCheckout.as_view()),

    path("lecturer/verify/", LecturerVerificationView.as_view()),
    path("lecturer/my-profile/", LecturerSelfProfileView.as_view()),
    path("lecturer/profile/<str:username>/", LecturerPublicProfileView.as_view()),
    path("lecturer/<str:username>/courses/", LecturerCoursesListView.as_view()),
    path("lecturer/edit-profile/", LecturerEditProfileView.as_view()),
    path("lecturer/job/<int:job_id>/apply/", LecturerApplyJobView.as_view()),
    path("lecturer/course/<int:course_id>/exam/create/", LecturerCreateExamView.as_view()),
    path("lecturer/exam/<int:exam_id>/grades/", LecturerAddGradesView.as_view()),
    path("lecturer/course/<int:course_id>/attendance/", LecturerMarkAttendanceView.as_view()),
    path("lecturer/schedule/", LecturerWeeklyScheduleView.as_view()),
    path("lecturer/exam/<int:exam_id>/grades/edit/", LecturerEditGradesView.as_view()),

    path("institution-lecturer/exams/", ExamsListView.as_view()),
    path("institution-lecturer/exam/<int:exam_id>/grades/view/", InstitutionOrLecturerViewGradesView.as_view()),
    path("institution-lecturer/course/<int:course_id>/attendance/<int:lecture_number>/", InstitutionOrLecturerViewLectureAttendanceView.as_view()),

    path("student/verify/", StudentVerificationView.as_view()),
    path("student/my-profile/", StudentSelfProfileView.as_view()),
    path("student/profile/<str:username>/", StudentPublicProfileView.as_view()),
    path("student/<str:username>/courses/", StudentCoursesListView.as_view()),
    path("student/edit-profile/", StudentEditProfileView.as_view()),
    path("student/course/<int:course_id>/attendance/", StudentViewAttendanceView.as_view()),
    path("student/course/<int:course_id>/grades/", StudentViewGradesView.as_view()),
    path("student/schedule/", StudentWeeklyScheduleView.as_view()),
    path("student/is-student-free/<int:course_id>/", StudentScheduleCheckView.as_view()),
    path("student/enroll/<int:course_id>/", StudentEnrollCourseNoPaymentView.as_view()), # Payment or No Payment
    path("student/is-enrolled/<int:course_id>/", StudentIsEnrolledToCourseView.as_view()),
    path("student/add-payment-method/", StudentSetupPaymentMethodView.as_view()),
]
